# --- General settings ---
url: "http://funbox.me"
baseurl: ""

title: Notas de vida
email: jim.zhan@me.com
description: Jim - Let's geek~

github_username:  jimzhan
google_analytics: UA-73392068-1

#navbar-links:
#    About Me: "about"

avatar: "/images/avatar.jpg"

# --- Footer settings ---
author:
    name: Jim Zhan
    github: jimzhan
    linkedin: jimzhan
    stackoverflow: 1192760/jim-zhan

# Select which links to show in the footer
footer-links-active:
  rss: false
  facebook: true
  email: false
  twitter: true
  google-plus: true
  github: true
  linkedin: true
  stackoverflow: false
  instagram: true
  reddit: false
  xing: false
  stackoverflow: true
  snapchat: false
  youtube: false
  spotify: false

# Select which share links to show in posts
share-links-active:
  twitter: true
  facebook: true
  google: true


# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
disqus: "funbox"


# Facebook App ID
# fb_app_id: ""

# Excerpt Word Length
# Truncates the excerpt to the specified number of words on the index page
excerpt_length: 50

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "Asia/Beijing"
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/
paginate: 5
paginate_path: "/pages/:num/"

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
